<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
  xmlns:html="http://www.w3.org/TR/REC-html40"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap | BunusRadar</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333333;
            background-color: #f7f9fa;
            margin: 0;
            padding: 40px 20px;
          }
          .container {
            max-width: 1000px;
            margin: 0 auto;
            background: #ffffff;
            border-radius: 8px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.05);
            overflow: hidden;
            border: 1px solid #e1e8ed;
          }
          .header {
            background-color: #1b2e67;
            color: #ffffff;
            padding: 30px 40px;
            border-bottom: 4px solid #f9b44d;
          }
          .header h1 {
            margin: 0 0 10px 0;
            font-size: 26px;
            font-weight: 800;
            letter-spacing: -0.5px;
          }
          .header h1 span {
            color: #f9b44d;
          }
          .header p {
            margin: 0;
            font-size: 13px;
            color: #d1d9e6;
            line-height: 1.6;
          }
          .header p a {
            color: #f9b44d;
            text-decoration: underline;
          }
          .stats {
            padding: 15px 40px;
            background-color: #f0f4f8;
            border-bottom: 1px solid #e1e8ed;
            font-size: 13px;
            color: #4a5568;
            font-weight: 600;
          }
          .table-wrapper {
            padding: 20px 40px 40px 40px;
            overflow-x: auto;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
          }
          th {
            text-align: left;
            padding: 12px 14px;
            background-color: #14234f;
            color: #ffffff;
            font-weight: 700;
            text-transform: uppercase;
            font-size: 11px;
            letter-spacing: 0.5px;
          }
          th:first-child {
            border-top-left-radius: 4px;
          }
          th:last-child {
            border-top-right-radius: 4px;
          }
          td {
            padding: 12px 14px;
            border-bottom: 1px solid #edf2f7;
            color: #4a5568;
          }
          tr:nth-child(even) {
            background-color: #fcfdfe;
          }
          tr:hover td {
            background-color: #f4f7fb;
          }
          td a {
            color: #1b2e67;
            text-decoration: none;
            font-weight: 600;
          }
          td a:hover {
            color: #f9b44d;
            text-decoration: underline;
          }
          .badge {
            display: inline-block;
            padding: 3px 8px;
            font-size: 11px;
            font-weight: 600;
            border-radius: 4px;
            background-color: #e2e8f0;
            color: #2d3748;
          }
          .badge-high {
            background-color: #feebc8;
            color: #744210;
          }
          .footer {
            padding: 20px 40px;
            background-color: #f7fafc;
            border-top: 1px solid #e1e8ed;
            text-align: center;
            font-size: 12px;
            color: #718096;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>XML Sitemap <span>| BunusRadar</span></h1>
            <p>
              Generated by Yoast-style SEO Engine for <strong>BunusRadar</strong>. This is an XML Sitemap, meant for consumption by search engines like Google, Bing, and DuckDuckGo.<br/>
              You can find more information about XML sitemaps at <a href="https://www.sitemaps.org" target="_blank" rel="noopener">sitemaps.org</a>.
            </p>
          </div>
          <div class="stats">
            Number of URLs in this XML sitemap: <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/>
          </div>
          <div class="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th width="55%">URL</th>
                  <th width="15%">Priority</th>
                  <th width="15%">Change Freq.</th>
                  <th width="15%">Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td>
                      <xsl:variable name="itemURL">
                        <xsl:value-of select="sitemap:loc"/>
                      </xsl:variable>
                      <a href="{$itemURL}">
                        <xsl:value-of select="sitemap:loc"/>
                      </a>
                    </td>
                    <td>
                      <xsl:choose>
                        <xsl:when test="sitemap:priority &gt;= 0.8">
                          <span class="badge badge-high"><xsl:value-of select="sitemap:priority"/></span>
                        </xsl:when>
                        <xsl:otherwise>
                          <span class="badge"><xsl:value-of select="sitemap:priority"/></span>
                        </xsl:otherwise>
                      </xsl:choose>
                    </td>
                    <td>
                      <span class="badge"><xsl:value-of select="sitemap:changefreq"/></span>
                    </td>
                    <td>
                      <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </div>
          <div class="footer">
            BunusRadar XML Sitemap Index • Formatted with Yoast SEO style XSL stylesheet
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
